### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by ParadoxalManiak** [j4mie/idiorm#309]
I really love this ORM, I've been using it for about 2 or 3 years in all types of projects from small apps to CMS platforms.
The problem is that it seems like this project is dead. No updates in 3 years and with PHP7 I'm afraid of compatibility issues or security exploits. I want to know if this ORM is still safe to use and stable with PHP7 or I should start looking for alternatives.

**Comment by treffynnon** [comment]
This is a fair question.

I've not yet run the test suite on PHP7 and as you've noticed I've not
gotten around to merging some of the outstanding pull requests.

Neither Jamie nor I use Idiorm in our work any more as we're not in PHP
shops.

Whilst I've fully intended to get around to a little maintenance I've not
had the time to do so yet with paid work, of course, taking priority.

I still try to reply to issues when I can and I do hope to get around to
merging those pull requests at some point.

That said the current version is considered stable and the API will not
change. Any further changes will strictly be bug fixes and no new features
will be added.

I hope that helps.

**Comment by tag** [comment]
I would very much like to see a newer version with PSR support, dropping <=v5.2, and a few other modernization changes, but such requests have been generally closed as wontfix. I too am not using PHP regularly anymore,  otherwise I'd take this on. I'm content with the API freeze, but I feel like modernizing the code would both slim it slightly and signal the active development developers desire before relying on a library.

@treffynnon is generally active in addressing issues, so in that sense it's an active project. Paris/Idiorm been stable for some time, so there isn't much need for ongoing development for currently supported PHP versions.

**Comment by treffynnon** [comment]
It was considered and I nearly started on a v2, but after discussing it
with Jamie and carefully weighing it up we decided that Idiorm and Paris
would be frozen. There were others out there already doing that work - most
notably the Eloquent ORM of the Laravel project - of taking Idiorms ideas
and modernising the the underlying code etc.

**Comment by treffynnon** [comment]
I have just released a version [1.5.2](https://github.com/j4mie/idiorm/releases/tag/v1.5.2) of Idiorm and an accompanying [1.5.5](https://github.com/j4mie/paris/releases/tag/v1.5.5) of Paris that includes all the relevant pull requests. So hopefully that helps a little.

**Comment by redaxmedia** [comment]
Hello,

what about creating a v2 branch and let people send pull requests to it? I think there are many people who like to keep Idiorm alive with a couple of hours of work. Migrating countless of projects to another ORM is more time consuming if you sum up all the work of each developer.

**Comment by treffynnon** [comment]
= "what about creating a v2 branch and let people send pull requests to it?"


There is a well established feature freeze in place rendering a semver
beginning with a 2 irrelevant. There won't be any breaking changes.


= "I think there are many people who like to keep Idiorm alive with a
couple of hours of work."


It is very much alive and I don't understand where you have got the
impression otherwise. Patches are still accepted, I respond to and close
issues, etc.

= "Migrating countless of projects to another ORM is more time consuming if
you sum up all the work of each developer."


I don't understand this statement. Why would you migrate? This is a
maintained and stable ORM. You could start new projects with something
else, but I see little reason to migrate.

This project has been in feature freeze for years now and it's not going to
change.

**Comment by redaxmedia** [comment]
Don't be angry. I did not say that this project is dead or unmaintained but in my opinion it needs some modernization to keep attractive for developers. There is also a slightly difference between "feature freeze" and a "code freeze" by the way.

> Neither Jamie nor I use Idiorm in our work any more as we're not in PHP shops.

That being said, think about a maintainer who has time for active development?

**Comment by treffynnon** [comment]
= "Don't be angry."

I am not. I am economical with pleasantries because this is rehashing
ground the project has been over before and time is better spent on other
aspects.

= "In my opinion it needs some modernization to keep attractive for
developers."

Attracting new developers would require this, yes, but idiorm is in
maintenance only mode now so this really isn't a major goal of the project
any more.


= "There is also a slightly difference between "feature freeze" and a "code
freeze" by the way."

Idiorm is only making patch releases on version 1.5.*. This means that
there will be no breaking changes or feature additions. So sticking to
semver means that by definition a v2 or v1.6 is not in scope. Feature
freeze means that there will be no increment of the minor release number.


= "Neither Jamie nor I use Idiorm in our work any more as we're not in PHP
shops.

That being said, think about a maintainer who has time for active
development?"

No, this is idiorm. It is stable and it has met its design goals. There is
no need for further feature development. Any bugs will be patched.

If someone really feels that this project should become something beyond
its original bounds then they should create a fork of the project. You do
not need to merge back into idiorm to do what you propose.
