### ISSUE TITLE
How can I Autoload Idiorm.php 

### ISSUE THREAD

**Issue by stephenaryee** [j4mie/idiorm#320]
Hi J4mie, 

Am using Idiorm.php in all my project,  and I Autoload MY Classes, but Any Time I Autoload Idiorm.php, it gives error.  Please how can I Autoload Idiorm.php in my other classes . Thanks a lot for this class

**Comment by tag** [comment]
I have no issues when using Composer. (Highly recommended.) Composer works well, and if you include it's autoload handler, everything works just fine.

For many open source libraries, it's best to use StackOverflow (etc.) for support, rather than opening a bug report.

Also, when requesting support, it's best practice to include minimal sample code, PHP version, and a complete error message so others can help you without guessing at your code.
