### ISSUE TITLE
Difference between raw_query and raw_execute

### ISSUE THREAD

**Issue by yu-coder** [j4mie/idiorm#352]
Hi, I want to know the difference **between** raw_query and **raw_execute**.
Does anyone know?

**Comment by treffynnon** [comment]
`raw_query` allows you to make use of parameter binding and associate the records with a database table so that you can later call the `save()` method on an item/record. Please see the documentation: https://idiorm.readthedocs.io/en/latest/querying.html#raw-queries

`raw_execute` takes a raw SQL string and executes it - it does not bind the results to a particular table so you cannot call the `save()` method on an item/record.
